export interface MusicTrack {
  id: string;
  title: string;
  artist: string;
  url: string;
  duration: number;
  album?: string;
  coverArt?: string;
}

export const MUSIC_LIBRARY: MusicTrack[] = [
  {
    id: 'spotify_1',
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 246,
    album: 'Rocky III Soundtrack',
  },
  {
    id: 'spotify_2',
    title: 'We Will Rock You',
    artist: 'Queen',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 122,
    album: 'News of the World',
  },
  {
    id: 'spotify_3',
    title: "Gonna Fly Now (Theme from Rocky)",
    artist: 'Bill Conti',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 168,
    album: 'Rocky Soundtrack',
  },
  {
    id: 'spotify_4',
    title: 'The Champion',
    artist: 'Carrie Underwood ft. Ludacris',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 183,
    album: 'Cry Pretty',
  },
  {
    id: 'spotify_5',
    title: 'Hall of Fame',
    artist: 'The Script ft. will.i.am',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 203,
    album: '#3',
  },
  {
    id: 'spotify_6',
    title: 'Lose Yourself',
    artist: 'Eminem',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 326,
    album: '8 Mile Soundtrack',
  },
  {
    id: 'spotify_7',
    title: "Can't Hold Us",
    artist: 'Macklemore & Ryan Lewis',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 258,
    album: 'The Heist',
  },
  {
    id: 'spotify_8',
    title: 'Remember the Name',
    artist: 'Fort Minor',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 218,
    album: 'The Rising Tied',
  },
  {
    id: 'spotify_9',
    title: 'Levels',
    artist: 'Avicii',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 203,
    album: 'Levels',
  },
  {
    id: 'spotify_10',
    title: 'Thunderstruck',
    artist: 'AC/DC',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 292,
    album: 'The Razors Edge',
  },
  {
    id: 'spotify_11',
    title: 'Survival',
    artist: 'Eminem',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 276,
    album: 'The Marshall Mathers LP 2',
  },
  {
    id: 'spotify_12',
    title: 'Till I Collapse',
    artist: 'Eminem ft. Nate Dogg',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 298,
    album: 'The Eminem Show',
  },
  {
    id: 'spotify_13',
    title: 'Believer',
    artist: 'Imagine Dragons',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: 204,
    album: 'Evolve',
  },
  {
    id: 'spotify_14',
    title: 'Waka Waka (This Time for Africa)',
    artist: 'Shakira',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: 202,
    album: '2010 FIFA World Cup',
  },
  {
    id: 'spotify_15',
    title: 'Wavin Flag',
    artist: "K'naan",
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    duration: 217,
    album: 'Troubadour',
  },
  {
    id: 'spotify_16',
    title: 'We Are The Champions',
    artist: 'Queen',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    duration: 179,
    album: 'News of the World',
  },
  {
    id: 'spotify_17',
    title: 'Counting Stars',
    artist: 'OneRepublic',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    duration: 257,
    album: 'Native',
  },
  {
    id: 'spotify_18',
    title: 'Centuries',
    artist: 'Fall Out Boy',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    duration: 234,
    album: 'American Beauty/American Psycho',
  },
  {
    id: 'spotify_19',
    title: 'Radioactive',
    artist: 'Imagine Dragons',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: 187,
    album: 'Night Visions',
  },
  {
    id: 'spotify_20',
    title: 'Pump It',
    artist: 'The Black Eyed Peas',
    url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: 213,
    album: 'Monkey Business',
  },
];
